# Generated by Selenium IDE
import pytest
import time
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestSeoallintitle():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seoallintitle(self):
    self.driver.get("https://www.google.com/webhp")
    self.driver.set_window_size(1050, 702)
    element = self.driver.find_element(By.ID, "L2AGLb").click()
    self.driver.find_element(By.NAME, "q").send_keys("allintitle: keyword")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.ID, "result-stats")
    text = element.text
    pattern = r"Environ (.*) résultats" 
    resultat = re.match(pattern, text)
    print(resultat.groups()[0].replace("\u202f", ""))



